import { createSupabaseServerClient } from '@/lib/supabase/server';
import { AnimeCard } from '@/components/AnimeCard';
export const revalidate=60;
export default async function BrowsePage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const filters=await searchParams; const db=await createSupabaseServerClient(); let query=db.from('anime').select('*').order('updated_at',{ascending:false}).limit(60);
  if(filters.year)query=query.eq('year',Number(filters.year)); if(filters.season)query=query.ilike('season',filters.season); if(filters.status)query=query.ilike('status',`%${filters.status}%`); if(filters.type)query=query.ilike('type',`%${filters.type}%`);
  if(filters.studio){const {data:s}=await db.from('studios').select('id').eq('slug',filters.studio).maybeSingle();if(s){const {data:links}=await db.from('anime_studios').select('anime_id').eq('studio_id',s.id);const ids=(links??[]).map((x:any)=>x.anime_id);query=query.in('id',ids.length?ids:['00000000-0000-0000-0000-000000000000']);}}
  if(filters.genre){const {data:g}=await db.from('genres').select('id').eq('slug',filters.genre).maybeSingle();if(g){const {data:links}=await db.from('anime_genres').select('anime_id').eq('genre_id',g.id);const ids=(links??[]).map((x:any)=>x.anime_id);query=query.in('id',ids.length?ids:['00000000-0000-0000-0000-000000000000']);}}
  const [{data:anime},{data:genres},{data:studios}]=await Promise.all([query,db.from('genres').select('*').order('name'),db.from('studios').select('*').order('name').limit(100)]); const years=Array.from({length:35},(_,i)=>new Date().getFullYear()-i);
  return <div className="pageWidth standalone"><div className="pageIntro"><span className="eyebrow">FIND YOUR NEXT SHOW</span><h1>Browse anime</h1><p>Filter the synchronized catalog without querying the source website from the browser.</p></div><form className="filters"><select name="genre" defaultValue={filters.genre??''}><option value="">All genres</option>{genres?.map((g:any)=><option key={g.id} value={g.slug}>{g.name}</option>)}</select><select name="year" defaultValue={filters.year??''}><option value="">All years</option>{years.map(y=><option key={y}>{y}</option>)}</select><select name="season" defaultValue={filters.season??''}><option value="">All seasons</option>{['Winter','Spring','Summer','Fall'].map(s=><option key={s}>{s}</option>)}</select><select name="status" defaultValue={filters.status??''}><option value="">Any status</option>{['Ongoing','Completed','Upcoming','Hiatus'].map(s=><option key={s}>{s}</option>)}</select><select name="type" defaultValue={filters.type??''}><option value="">All types</option>{['TV','Movie','OVA','ONA','Special'].map(s=><option key={s}>{s}</option>)}</select><select name="studio" defaultValue={filters.studio??''}><option value="">Any studio</option>{studios?.map((s:any)=><option key={s.id} value={s.slug}>{s.name}</option>)}</select><button className="primaryBtn">Apply filters</button></form><p className="resultCount">{anime?.length??0} results shown</p><div className="browseGrid">{anime?.map((a:any)=><AnimeCard key={a.id} anime={a}/>)}</div>{!anime?.length&&<div className="emptyState"><h2>No matches</h2><p>Try broadening one of the filters.</p></div>}</div>;
}
