-- Facebook detection is independent. Website episodes provide canonical metadata only.
create table if not exists public.facebook_discovery_candidates(source_url text primary key,title text not null default '',episode_number numeric,discovered_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),matched_episode_id uuid references public.episodes(id) on delete set null,status text not null default 'detected' check(status in ('detected','matched','queued','published','ignored')),last_error text);
create index if not exists facebook_discovery_candidates_status_idx on public.facebook_discovery_candidates(status,discovered_at);
alter table public.facebook_discovery_candidates enable row level security;
revoke all on public.facebook_discovery_candidates from anon,authenticated; grant all on public.facebook_discovery_candidates to service_role;
create or replace function public.reconcile_facebook_discovery_candidates() returns integer language plpgsql security definer set search_path=public as $$ declare c record;e record;n integer:=0;begin for c in select * from public.facebook_discovery_candidates where status in ('detected','matched') order by discovered_at loop select id into e from public.episodes where source_url=c.source_url limit 1;if e.id is not null then insert into public.facebook_episode_queue(episode_id,episode_url,status,priority) values(e.id,c.source_url,'pending',0) on conflict(episode_id) do update set priority=least(public.facebook_episode_queue.priority,0),updated_at=now();update public.facebook_discovery_candidates set matched_episode_id=e.id,status='queued',last_seen_at=now(),last_error=null where source_url=c.source_url;n:=n+1;end if;end loop;return n;end $$;
revoke all on function public.reconcile_facebook_discovery_candidates() from public,anon,authenticated;grant execute on function public.reconcile_facebook_discovery_candidates() to service_role;
create or replace function public.queue_facebook_candidate_after_episode() returns trigger language plpgsql security definer set search_path=public as $$ declare c record;begin select * into c from public.facebook_discovery_candidates where source_url=new.source_url limit 1;if c.source_url is not null and not exists(select 1 from public.facebook_episode_publications where episode_id=new.id) then insert into public.facebook_episode_queue(episode_id,episode_url,status,priority) values(new.id,new.source_url,'pending',0) on conflict(episode_id) do update set priority=least(public.facebook_episode_queue.priority,0),updated_at=now();update public.facebook_discovery_candidates set matched_episode_id=new.id,status='queued',last_seen_at=now(),last_error=null where source_url=new.source_url;end if;return new;end $$;
revoke all on function public.queue_facebook_candidate_after_episode() from public,anon,authenticated;
drop trigger if exists trg_queue_new_episode_for_facebook on public.episodes;drop trigger if exists trg_queue_facebook_candidate_after_episode on public.episodes;
create trigger trg_queue_facebook_candidate_after_episode after insert or update of source_url on public.episodes for each row execute function public.queue_facebook_candidate_after_episode();