import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;
const publishable=process.env.SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const secret=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;
const cronSecret=process.env.SYNC_CRON_SECRET;
assert(url&&publishable&&secret&&cronSecret,'SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, SUPABASE_SECRET_KEY and SYNC_CRON_SECRET are required');
const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
const out=[];
function ok(name,details={}){out.push({name,status:'PASS',...details});console.log(`PASS ${name}`,details)}
function skip(name,reason){out.push({name,status:'SKIP',reason});console.log(`SKIP ${name}: ${reason}`)}
async function invokeCron(name){const r=await fetch(`${url}/functions/v1/${name}`,{method:'POST',headers:{'content-type':'application/json','x-cron-secret':cronSecret},body:'{}'});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`${name}: ${r.status} ${JSON.stringify(body)}`);return body}
async function makeUser(tag){const email=`qa-${tag}-${Date.now()}-${randomBytes(3).toString('hex')}@example.com`;const password=`Qa!${randomBytes(18).toString('base64url')}`;const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true});if(error)throw error;const client=createClient(url,publishable,{auth:{persistSession:false,autoRefreshToken:false}});const {data:login,error:loginError}=await client.auth.signInWithPassword({email,password});if(loginError)throw loginError;return {id:data.user.id,email,password,client,token:login.session.access_token}}
async function adminAction(token,action,extra={}){const r=await fetch(`${url}/functions/v1/admin-sync`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({action,...extra})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`admin-sync ${action}: ${r.status} ${JSON.stringify(body)}`);return body}
async function readyPending(){const {count,error}=await admin.from('sync_queue').select('*',{head:true,count:'exact'}).eq('status','pending').lte('available_at',new Date().toISOString());if(error)throw error;return count??0}
async function drain(limit=Number(process.env.MAX_WORKER_PASSES||400)){let passes=0,idle=0;while(passes<limit){const before=await readyPending();if(before===0)break;const r=await invokeCron('worker');passes++;if((r.processed??0)===0){idle++;if(idle>=3)break}else idle=0;}return passes}

let qaAdmin,userA,userB;
try{
  qaAdmin=await makeUser('admin');
  const {error:promoteError}=await admin.from('admin_users').insert({user_id:qaAdmin.id});if(promoteError)throw promoteError;
  const boot=await adminAction(qaAdmin.token,'bootstrap');
  assert((boot.catalogFound??0)>0,'bootstrap did not discover anime');
  await drain();
  const [{count:animeCount},{count:episodeCount},{count:videoCount}]=await Promise.all([admin.from('anime').select('*',{head:true,count:'exact'}),admin.from('episodes').select('*',{head:true,count:'exact'}),admin.from('video_sources').select('*',{head:true,count:'exact'})]);
  assert((animeCount??0)>0);assert((episodeCount??0)>0);assert((videoCount??0)>0);ok('Test 1 initial import',{anime:animeCount,episodes:episodeCount,videoSources:videoCount});
  const beforeA=animeCount,beforeE=episodeCount;await invokeCron('scanner');await drain();const scan2=await invokeCron('scanner');
  const [{count:afterA},{count:afterE}]=await Promise.all([admin.from('anime').select('*',{head:true,count:'exact'}),admin.from('episodes').select('*',{head:true,count:'exact'})]);
  assert.equal(afterA,beforeA);assert.equal(afterE,beforeE);assert.equal(Number(scan2.new??0),0);ok('Test 2 idempotent repeat scan',{anime:afterA,episodes:afterE,scannerNew:scan2.new??0});
  if(process.env.TEST_NEW_EPISODE_URL){const u=process.env.TEST_NEW_EPISODE_URL;const {data:existing}=await admin.from('episodes').select('id').eq('source_url',u).maybeSingle();assert(!existing);await adminAction(qaAdmin.token,'sync_url',{url:u});await drain();const {data:created}=await admin.from('episodes').select('id').eq('source_url',u).maybeSingle();assert(created);ok('Test 3 new episode ingestion',{sourceUrl:u})}else skip('Test 3 new episode discovery','Set TEST_NEW_EPISODE_URL to a newly published source episode to run the live release test.');
  const {data:sampleAnime}=await admin.from('anime').select('id,title,source_url').limit(1).single();const originalTitle=sampleAnime.title;await admin.from('anime').update({title:'__QA_STALE_METADATA__'}).eq('id',sampleAnime.id);await adminAction(qaAdmin.token,'sync_url',{url:sampleAnime.source_url});await drain();const {data:restored}=await admin.from('anime').select('title').eq('id',sampleAnime.id).single();assert.equal(restored.title,originalTitle);ok('Test 4 metadata resynchronization',{anime:originalTitle});
  const sourceOrigin=new URL(sampleAnime.source_url).origin;const badUrl=`${sourceOrigin}/qa-malformed-episode-99999999/`;await admin.from('sync_queue').insert({source_url:badUrl,source_id:'episode:qa-malformed-episode-99999999',item_type:'episode',status:'pending',priority:1,max_attempts:2});await adminAction(qaAdmin.token,'sync_url',{url:sampleAnime.source_url});await invokeCron('worker');const {data:bad}=await admin.from('sync_queue').select('status,last_error,attempts').eq('source_url',badUrl).order('created_at',{ascending:false}).limit(1).single();const {data:good}=await admin.from('sync_queue').select('status').eq('source_url',sampleAnime.source_url).order('created_at',{ascending:false}).limit(1).single();assert(['pending','failed'].includes(bad.status));assert(bad.last_error);assert.equal(good.status,'completed');ok('Test 5 malformed page isolation',{badStatus:bad.status,attempts:bad.attempts});
  userA=await makeUser('a');userB=await makeUser('b');const {data:episode}=await admin.from('episodes').select('id,anime_id').limit(1).single();assert(episode);let r=await userA.client.from('favorites').insert({user_id:userA.id,anime_id:episode.anime_id});if(r.error)throw r.error;r=await userA.client.from('watch_history').upsert({user_id:userA.id,anime_id:episode.anime_id,episode_id:episode.id,watched_at:new Date().toISOString()},{onConflict:'user_id,episode_id'});if(r.error)throw r.error;r=await userA.client.from('playback_progress').upsert({user_id:userA.id,anime_id:episode.anime_id,episode_id:episode.id,position_seconds:42,duration_seconds:120,completed:false},{onConflict:'user_id,episode_id'});if(r.error)throw r.error;const {data:aProgress}=await userA.client.from('playback_progress').select('*').eq('episode_id',episode.id).single();assert.equal(Number(aProgress.position_seconds),42);ok('Test 6 watch progress and history',{position:Number(aProgress.position_seconds)});
  const [{data:bFav},{data:bHist},{data:bProg}]=await Promise.all([userB.client.from('favorites').select('*').eq('user_id',userA.id),userB.client.from('watch_history').select('*').eq('user_id',userA.id),userB.client.from('playback_progress').select('*').eq('user_id',userA.id)]);assert.equal(bFav.length,0);assert.equal(bHist.length,0);assert.equal(bProg.length,0);await userB.client.from('favorites').delete().eq('user_id',userA.id).eq('anime_id',episode.anime_id);const {data:stillThere}=await userA.client.from('favorites').select('*').eq('anime_id',episode.anime_id).single();assert(stillThere);ok('Test 7 cross-user RLS isolation');
  console.table(out);
} finally { for(const u of [userA,userB,qaAdmin])if(u?.id)await admin.auth.admin.deleteUser(u.id).catch(()=>{}); }
