import { chromium } from "playwright";
const base="https://animepahe.pw";
const browser=await chromium.launch({headless:true});
const page=await browser.newPage();
const hits=[];
page.on("response",r=>{const u=r.url();if(/animepahe|kwik|\.m3u8|\.mp4|play|episode/i.test(u))hits.push({status:r.status(),url:u})});
await page.goto(base,{waitUntil:"domcontentloaded",timeout:60000});await page.waitForTimeout(3000);
const latest=await page.locator("a").evaluateAll(as=>as.map(a=>({text:(a.textContent||"").replace(/\s+/g," ").trim(),href:a.href})).filter(x=>x.href&&/animepahe\.pw/.test(x.href)&&x.text).slice(0,250));
console.log("ANIMEPAHE_LATEST_JSON="+JSON.stringify(latest));
console.log("ANIMEPAHE_NETWORK_JSON="+JSON.stringify(hits.slice(-150)));
await browser.close();