-- Base schema for first-party analytics and submitted-search telemetry.
-- Kept separate from admin summary migrations so a fresh database can replay cleanly.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text not null,
  event_name text not null check (event_name in ('page_view','anime_view','play_start','play_25','play_50','play_75','play_complete','source_change')),
  anime_id uuid references public.anime(id) on delete set null,
  episode_id uuid references public.episodes(id) on delete set null,
  source_id uuid references public.video_sources(id) on delete set null,
  path text,
  referrer_host text,
  device_type text,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_session_idx on public.analytics_events(session_id,created_at desc);
create index if not exists analytics_events_anime_idx on public.analytics_events(anime_id,created_at desc);
alter table public.analytics_events enable row level security;
drop policy if exists "analytics insert" on public.analytics_events;
create policy "analytics insert" on public.analytics_events for insert to anon,authenticated with check (user_id is null or user_id=auth.uid());
drop policy if exists "admin analytics read" on public.analytics_events;
create policy "admin analytics read" on public.analytics_events for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  query text not null,
  result_count integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists search_events_created_idx on public.search_events(created_at desc);
create index if not exists search_events_query_idx on public.search_events(lower(query),created_at desc);
alter table public.search_events enable row level security;
drop policy if exists "search_events_insert" on public.search_events;
create policy "search_events_insert" on public.search_events for insert to anon,authenticated with check (length(query)>=2 and length(query)<=160 and result_count>=0 and result_count<=50);
drop policy if exists "search_events_admin_read" on public.search_events;
create policy "search_events_admin_read" on public.search_events for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
