revoke execute on function public.touch_updated_at() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.is_admin() from public, anon, authenticated;
revoke execute on function public.claim_sync_jobs(int) from public, anon, authenticated;
revoke execute on function public.recover_stale_sync_jobs(interval) from public, anon, authenticated;
revoke execute on function public.enqueue_sync_job(text,text,public.sync_item_type,int) from public, anon, authenticated;
revoke execute on function public.record_source_discoveries(jsonb) from public, anon, authenticated;
revoke execute on function public.enqueue_stale_catalog() from public, anon, authenticated;
revoke execute on function public.invoke_sync_edge(text) from public, anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.search_anime(text,int) to anon, authenticated;
grant execute on function public.claim_sync_jobs(int) to service_role;
grant execute on function public.recover_stale_sync_jobs(interval) to service_role;
grant execute on function public.enqueue_sync_job(text,text,public.sync_item_type,int) to service_role;
grant execute on function public.record_source_discoveries(jsonb) to service_role;
grant execute on function public.enqueue_stale_catalog() to service_role;
grant execute on function public.invoke_sync_edge(text) to postgres, service_role;
grant select on public.anime, public.anime_titles, public.episodes, public.video_sources, public.genres, public.anime_genres, public.studios, public.anime_studios, public.characters, public.anime_characters, public.voice_actors, public.character_voice_actors, public.related_anime to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant select, update on public.profiles to authenticated;
grant select on public.admin_users to authenticated;
grant select, insert, update, delete on public.favorites, public.watch_history, public.playback_progress to authenticated;
grant select on public.continue_watching to authenticated;
grant select on public.source_items, public.sync_queue, public.sync_runs, public.sync_events to authenticated;
revoke insert, update, delete on public.anime, public.anime_titles, public.episodes, public.video_sources, public.genres, public.anime_genres, public.studios, public.anime_studios, public.characters, public.anime_characters, public.voice_actors, public.character_voice_actors, public.related_anime, public.source_items, public.sync_runs, public.sync_events from anon, authenticated;
revoke insert, delete on public.sync_queue from anon, authenticated;
revoke update on public.sync_queue from anon;
