create table if not exists public.facebook_sync_sources (
 id bigint generated by default as identity primary key,
 name text not null,
 source_url text not null unique,
 source_type text not null default 'facebook_page',
 enabled boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.facebook_sync_sources enable row level security;
revoke all on public.facebook_sync_sources from anon, authenticated;
insert into public.facebook_sync_sources(name,source_url)
values ('Fin Sensei','https://www.facebook.com/profile.php?id=61569593189979')
on conflict(source_url) do nothing;
alter table public.facebook_sync_items add column if not exists content_fingerprint text;
alter table public.facebook_sync_items add column if not exists canonical_item_id bigint references public.facebook_sync_items(id);
create unique index if not exists facebook_sync_media_hash_unique on public.facebook_sync_items(media_hash) where media_hash is not null and canonical_item_id is null;
create index if not exists facebook_sync_fingerprint_idx on public.facebook_sync_items(content_fingerprint) where content_fingerprint is not null;
create index if not exists facebook_sync_source_page_idx on public.facebook_sync_items(source_page);
