-- Facebook Page video synchronization queue.
-- Source media is only processed when it has been acquired through an authorized mechanism.

create table if not exists public.facebook_sync_items (
  id bigint generated by default as identity primary key,
  source_page text not null,
  source_post_id text,
  source_video_id text,
  source_url text not null,
  source_caption text,
  source_published_at timestamptz,
  media_url text,
  media_hash text,
  destination_page_id text not null,
  destination_video_id text,
  destination_url text,
  status text not null default 'detected'
    check (status in ('detected','media_ready','uploading','published','retry','failed','skipped')),
  retry_count integer not null default 0,
  last_error text,
  detected_at timestamptz not null default now(),
  downloaded_at timestamptz,
  uploaded_at timestamptz,
  next_attempt_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists facebook_sync_items_source_post_uidx
  on public.facebook_sync_items (source_page, source_post_id)
  where source_post_id is not null;
create unique index if not exists facebook_sync_items_source_video_uidx
  on public.facebook_sync_items (source_page, source_video_id)
  where source_video_id is not null;
create index if not exists facebook_sync_items_work_idx
  on public.facebook_sync_items (status, next_attempt_at, detected_at);

alter table public.facebook_sync_items enable row level security;
revoke all on public.facebook_sync_items from anon, authenticated;

create or replace function public.touch_facebook_sync_item()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists trg_touch_facebook_sync_item on public.facebook_sync_items;
create trigger trg_touch_facebook_sync_item
before update on public.facebook_sync_items
for each row execute function public.touch_facebook_sync_item();
